fastlane_version "1.46.1"

platform :ios do
                
        lane :beta do
            increment_build_number(
              xcodeproj: './ios/testapp.xcodeproj'
            )

            sh("xctool -project ../ios/testapp.xcodeproj -scheme testapp clean archive -archivePath ../build/testapp")

            sh("xcodebuild -exportArchive -exportFormat ipa -archivePath ../build/testapp.xcarchive -exportPath ../build/testapp.ipa -exportProvisioningProfile 'iOS Team Provisioning Profile: *'")        

            sh("cp ../build/testapp.ipa $BITRISE_DEPLOY_DIR")
        end

end